site_name: antiSMASH Documentation
nav:
    - Home: index.md
    - Using antiSMASH:
      - Introduction: intro.md
      - Submitting jobs on the website: website_submission.md
      - Understanding the output: understanding_output.md
      - Loading external results: sideloading.md
    - Module-specific information:
       - BGC detection: clusterrules.md
       - NRPS/PKS domains: modules/nrps_pks_domains.md
       - NRPS/PKS modules: modules/nrps_pks_modules.md
       - PKS type II: modules/t2pks.md
    - Local antiSMASH installation:
        - Installation: install.md
        - Starting command line runs: command_line.md
    - antiSMASH5 feature list: antiSMASH5features.md
    - Change log:
        - 5.1: changelog/5.1.md
        - 5.2: changelog/5.2.md
        - 6.0: changelog/6.0.md
    - FAQ: faq.md
    - Glossary: glossary.md
    - About: about.md
theme:
    name: readthedocs
    custom_dir: custom_theme
markdown_extensions:
    - footnotes
    - toc:
        permalink: "#"
plugins:
  - search
  - git-revision-date
extra_css:
  - css/extra.css
